const ACTION_TYPE = {
  // COUNTER ACTION TYPES
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',
  // HEROES ACTION TYPES
  CREATE_HERO: 'CREATE_HERO', // DISPATCHED FROM VIEW
  // DISPATCHED FROM SAGA
  CREATE_HERO_REQUEST: 'CREATE_HERO_REQUEST',
  CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
  CREATE_HERO_ERROR: 'CREATE_HERO_ERROR',
  // GET HEROES
  GET_HEROES: 'GET_HEROES',
  GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
  GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
  GET_HEROES_ERROR: 'GET_HEROES_ERROR',
};

export default ACTION_TYPE;
